#!/bin/bash
DIR=$(cd "$(dirname "$0")"; pwd)

# install python3-venv
sudo apt-get install -y python3-venv

# create venv
python3 -m venv ${DIR}/venv
source ${DIR}/venv/bin/activate
pip install -r ${DIR}/requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple

# create systemd service
cat << EOF | sudo tee /lib/systemd/system/clash-config-merger.service
[Unit]
Description=Clash Config Merger Service
After=network.target

[Service]
Type=simple
Restart=on-failure
RestartSec=5s
WorkingDirectory=${DIR}
ExecStart=${DIR}/venv/bin/python ${DIR}/clash-config-merger
LimitNOFILE=1048576

[Install]
WantedBy=multi-user.target
EOF

sudo systemctl daemon-reload
sudo systemctl enable clash-config-merger.service
sudo systemctl restart clash-config-merger.service
